# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ArheoloskiGis
                                 A QGIS plugin
 This plugin loads useful layers
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-02-22
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Matjaž Mori, ZVKDS CPA
        email                : matjaz.mori@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, pyqtSignal, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QDockWidget, QTabWidget, QWidget, QVBoxLayout
from qgis.core import (QgsProject, QgsCoordinateReferenceSystem, QgsCoordinateTransform)
   
import os.path


from .externals import pn_path, access
import webbrowser

# Import the code for the dialog
from .agis_work_loader.agis_work_loader import ArheoloskiGisWorkLoader
from .tab_nalozi_sloje import TabNaloziSloje
from .tab_iskalnik import TabIskalnik
from .tab_o_vticniku import TabOVticniku


class ArheoloskiGis:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir, 'i18n', f'ArheoloskiGis_{locale}.qm')
        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)
        self.actions = []
        self.menu = self.tr('AGIS')
        self.toolbar = self.iface.addToolBar('AGIS')
        self.toolbar.setObjectName('AGIS')
        self.pluginIsActive = False
        self.dockwidget = None

        
        if access(self):
            self.work_loader_icon = str(pn_path('icons')/'icon_work_loader.png')
            self.Work_loader = QAction(QIcon(self.work_loader_icon), self.tr("Naloži delovne sloje"), self.iface.mainWindow())
            self.Work_loader.triggered.connect(self.work_loader)
            self.toolbar.addAction(self.Work_loader)
            self.actions.append(self.Work_loader)

        self.arcanum_loader_icon = str(pn_path('icons')/'icon_arcanum_loader.png')
        self.Arcanum = QAction(QIcon(self.arcanum_loader_icon), self.tr("Arcanum"), self.iface.mainWindow())
        self.Arcanum.triggered.connect(self.arcanum)
        self.toolbar.addAction(self.Arcanum)
        self.actions.append(self.Arcanum)




    def tr(self, message):
        return QCoreApplication.translate('ArheoloskiGis', message)

    def add_action(self, icon_path, text, callback, parent=None):
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        self.toolbar.addAction(action)
        self.iface.addPluginToWebMenu(self.menu, action)
        self.actions.append(action)
        return action

    def initGui(self):
        # Add AGIS icon to toolbar, clicking it opens the AGIS dock widget
        icon_path = str(pn_path('icons')/'icon_load.png')
        self.agis_toolbar_action = QAction(QIcon(icon_path), self.tr('AGIS'), self.iface.mainWindow())
        self.agis_toolbar_action.triggered.connect(self.run)
        self.toolbar.addAction(self.agis_toolbar_action)
        self.iface.addPluginToWebMenu(self.menu, self.agis_toolbar_action)
        self.actions.append(self.agis_toolbar_action)
        # Automatically open the AGIS panel on plugin load
        self.run()

    def unload(self):
        for action in self.actions:
            self.iface.removePluginWebMenu(self.menu, action)
            self.toolbar.removeAction(action)

        if self.toolbar:
            self.iface.mainWindow().removeToolBar(self.toolbar)
            self.toolbar = None

        # ⭐ IMPORTANT PART
        if self.dockwidget:
            self.iface.removeDockWidget(self.dockwidget)
            self.dockwidget.deleteLater()
            self.dockwidget = None
            self.pluginIsActive = False



    def run(self):
        if not self.pluginIsActive:
            self.pluginIsActive = True
            if self.dockwidget is None:
                self.dockwidget = AgisDockWidget(self.iface, self.iface.mainWindow())
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)
            self.dockwidget.show()

    def onClosePlugin(self):
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)
        self.pluginIsActive = False




    def arcanum(self):
        #Get bounding box and transform to WGS84 pseudo
        crsSrc = self.iface.mapCanvas().mapSettings().destinationCrs().authid()
        crsSrc = QgsCoordinateReferenceSystem(crsSrc)
        crsDest = QgsCoordinateReferenceSystem("EPSG:3857")
        transform = QgsCoordinateTransform(crsSrc, crsDest, QgsProject.instance())
        bbox = self.iface.mapCanvas().extent()
        e = transform.transformBoundingBox(bbox)
        xmin = e.xMinimum()
        ymin = e.yMinimum()
        xmax = e.xMaximum()
        ymax = e.yMaximum()
 
 
        part_one = 'https://mapire.eu/en/map/cadastral/?bbox='
        sep = '%2C'
        part_three = '&map-list=1&layers=here-aerial%2C3%2C4'
        link = '%s%s%s%s%s%s%s%s%s' %(part_one, xmin, sep, ymin, sep, xmax, sep, ymax,part_three) 
        webbrowser.open(link)
        pass

    
    def work_loader(self):
        ld = ArheoloskiGisWorkLoader(self.iface)
        ld.run()



class AgisDockWidget(QDockWidget):
    closingPlugin = pyqtSignal()

    def __init__(self, iface, parent=None):
        super().__init__(parent)
        self.iface = iface
        self.setWindowTitle("AGIS")
        self.main_widget = QWidget()
        self.setWidget(self.main_widget)

 
        layout = QVBoxLayout(self.main_widget)
        layout.setContentsMargins(0, 0, 0, 0)
        
        # Create tab widget
        self.tabs = QTabWidget()
        layout.addWidget(self.tabs)

        # Add main tabs

        self.tabs.addTab(TabNaloziSloje(iface), self.tr("Naloži sloje"))
        self.tabs.addTab(TabIskalnik(iface), self.tr("eArheologija"))
        self.tabs.addTab(TabOVticniku(iface), self.tr("Pomoč"))

        self.iface.addDockWidget(Qt.DockWidgetArea.RightDockWidgetArea, self)


    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()